name: golangci-lint
on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'

      - name: Setup workspace
        run: go work init

      - name: Add all modules to workspace
        run: go work use -r .

      - name: Lint patterns
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
          args: ./patterns/*

      - name: Lint dev_challenges
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
          args: ./dev_challenges/**/

      - name: Lint dev_challenges (sortcli)
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
          args: ./dev_challenges/sortcli/...

      - name: Lint spoken_tasks
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
          args: ./spoken_tasks/*
