name: Nilaway lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Setup workspace
      run: go work init

    - name: Add all modules to workspace
      run: go work use -r .

    - name: Install nilaway
      run: go install go.uber.org/nilaway/cmd/nilaway@latest

    - name: Run nilaway on dev_challenges
      run: nilaway ./...
